AlumniTrackerSite/Controllers/AlumniUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlumniTrackerSite.Contexts;
using AlumniTrackerSite.Models;
using static AlumniTrackerSite.Data.Security;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using AlumniTrackerSite.Data;
using System.Text.RegularExpressions;
using System.Text;

namespace AlumniTrackerSite
{
    public class AlumniUsersController : Controller
    {
        private readonly TrackerContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<AlumniUsersController> _logger;
        RoleManager<IdentityRole> _roleManager;

        public AlumniUsersController(TrackerContext context, UserManager<IdentityUser> userManager, ILogger<AlumniUsersController> logger, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
            _roleManager = roleManager;
        }
        [Authorize(Roles = "SuperAdmin")]
        public FileStreamResult CSV()
        {
            // Would combine these, except this method can not pass _context without being non static
            return CSVBuilder.MakeCSV(_context); ;
        }
        // GET: AlumniUsers
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Index()//replace this to be search, and then use general input?
        {
            return _context.GetAlumnis() != null ?
                        View(_context.GetAlumnis()) :
                        Problem("Entity set 'TrackerContext.AlumniUsers'  is null.");
        }

        [HttpPost]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Index(string SearchPhrase, string type)
        {
            return View(SearchHelper(SearchPhrase, type));
        }
        public IEnumerable<Alumnis> SearchHelper(string Phrase, string Type)
        {
            // currently there is no error being sent to the user. So these are confusing to a user.
            if (Phrase == null || Phrase == "") return _context.GetAlumnis();
            if (!GeneralInput(_logger, Phrase)) return _context.GetAlumnis();
            if (!GeneralInput(_logger, Type)) return  _context.GetAlumnis();


            // Set up Regex, this only allows * to be used as a single character wildcard.
            Phrase = Phrase.Replace("*", ".").ToLower();
            Regex reg = new Regex(Phrase);

            if (Phrase != null)
            {
                switch (Type)
                {
                    case "studentid":   // find alumni who have this exact studentid
                        return (_context.GetAlumnis()
                            .Where(c => c.StudentId.ToLower() == Phrase.ToLower()));

                    case "name":
                        return (_context.GetAlumnis()
                            .Where(c => reg.IsMatch(c.Name.ToLower())));

                        // all of these search terms can be null. Which will throw an exception if not handled
                    case "employer":
                        return (_context.GetAlumnis()
                            .Where(c =>
                            {
                                if(c.EmployerName != null) 
                                { return reg.IsMatch(c.EmployerName.ToLower()); }
                                return false;
                            }));

                    case "yeargrad":
                        return (_context.GetAlumnis()
                            .Where(c =>
                            {
                                if (c.YearGraduated != null) 
                                { return reg.IsMatch(c.YearGraduated.ToLower()); }
                                return false;
                            }));

                    case "degree":
                        return (_context.GetAlumnis()
                            .Where(c =>
                            {
                                if (c.Degree != null) 
                                { return reg.IsMatch(c.Degree.ToLower()); }
                                return false;
                            }));

                    default:
                        return _context.GetAlumnis();
                }
            }
            return _context.GetAlumnis(); // Returns Full list

        }
        // GET: AlumniUsers/Details/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Details(string? idString)
        {
            if (idString == null || _context.AlumniUsers == null)
            {
                return NotFound();
            }

            var alumniUser = await _context.AlumniUsers
                .FirstOrDefaultAsync(m => m.StudentId.Equals(idString));
            if (alumniUser == null)
            {
                return NotFound();
            }

            return View(alumniUser);
        }

        // GET: AlumniUsers/Create
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Create() // unused page
        {
            return View();
        }


// Not in use and is not functional, currently the register page is used instead
        //// POST: AlumniUsers/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin,SuperAdmin")]
        //public async Task<IActionResult> Create([Bind("StudentId,Name,EmployerName,FieldofEmployment,YearGraduated,Degree,Notes,DateModified,Address,City,State,Zip,Phone,AlumniId,Id")] AlumniUser alumniUser, [Bind("Email")] string  email)
        //{
        //    if (!CheckInputs(_logger, alumniUser))
        //    { return View(); } // Change to error
        //    if (ModelState.IsValid)
        //    {
        //        alumniUser.DateModified = DateTime.Today;
        //        alumniUser.Id = _userManager.GetUserId(User);
        //        if(_context.AlumniUsers.Where(m => m.Id.Equals(alumniUser.Id)).Any() || alumniUser.Id == null)
        //        {
        //            //return 
        //        }
        //        _context.Add(alumniUser);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(alumniUser);
        //}

        public string GetName(int id)
        {
            //some code to get alumniuser identity user
            if (id == 0 || _context.AlumniUsers == null)
            {
                return "not found";
            }
            return "yes";

        }


        // GET: AlumniUsers/Edit/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null || _context.AlumniUsers == null)
            {
                return NotFound();
            }

            var alumniUser = await _context.AlumniUsers.FindAsync(id);
            if (alumniUser == null)
            {
                return NotFound();
            }
            return View(alumniUser);
        }

        // POST: AlumniUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Edit(string id, [Bind("StudentId,Name,EmployerName,FieldofEmployment,YearGraduated,Degree,Notes,DateModified,Address,City,State,Zip,Phone,AlumniId,Id")] AlumniUser alumniUser)
        {
            if (id != alumniUser.Id)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    alumniUser.DateModified = DateTime.Today;
                    _context.Update(alumniUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlumniUserExists(alumniUser.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alumniUser);
        }

        // GET: AlumniUsers/Delete/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AlumniUsers == null)
            {
                return NotFound();
            }

            var alumniUser = await _context.AlumniUsers
                .FirstOrDefaultAsync(m => m.AlumniId == id);
            if (alumniUser == null)
            {
                return NotFound();
            }

            return View(alumniUser);
        }

        // POST: AlumniUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (_context.AlumniUsers == null)
            {
                return Problem("Entity set 'TrackerContext.AlumniUsers'  is null.");
            }
            AlumniUser? alumniUser = await _context.AlumniUsers.Where(c => c.AlumniId == id).FirstOrDefaultAsync();
            if (alumniUser != null)
            {
                 IdentityUser user = await _userManager.FindByIdAsync(alumniUser.Id);

AlumniTrackerSite/Controllers/RoleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using AlumniTrackerSite.Models;
using AlumniTrackerSite.Data;
using AlumniTrackerSite.Contexts;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AlumniTrackerSite.Controllers
{
    public class RoleController : Controller
    {
        private readonly TrackerContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<AlumniUsersController> _logger;
        private RoleManager<IdentityRole> roleManager;

        public RoleController(TrackerContext context, UserManager<IdentityUser> userManager, ILogger<AlumniUsersController> logger, RoleManager<IdentityRole> roleMgr)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
            roleManager = roleMgr;
        }

        [Authorize(Policy = "Administrator")]
        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<IdentityUser> members = new List<IdentityUser>();
            List<IdentityUser> nonMembers = new List<IdentityUser>();
            foreach (IdentityUser user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }
        [Authorize(Policy = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }                
            }
            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }
        // GET: RoleController
        [Authorize(Policy = "readpolicy")]
        public ViewResult Index() => View(roleManager.Roles);
        
        // GET: RoleController/Details/5
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: RoleController/Create
        [Authorize(Policy = "Administrator")]
        public ActionResult Create()
        {
            return View(new IdentityRole());
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrator")]
        public ActionResult Create(IdentityRole Role
            )
        {
            _context.Roles.Add(Role);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: RoleController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View(id);
        //}

        //// POST: RoleController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: RoleController/Delete/5
        [Authorize(Policy = "Administrator")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RoleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrator")]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", roleManager.Roles);
        }
        [Authorize(Roles = "SuperAdmin")]
        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }
}

AlumniTrackerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlumniSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlumniSite.styles.css" asp-append-version="true" />
</head>
<body>

    <header class="col-md-8 offset-2">
        <nav class="navbar navbar-expand-sm col-md-12">
            <div class="col-md-12">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/Alumni-Logo-01.png" /></a>
                <div class="float-right">
                    <div class="float-right">
                        <ul class="navbar-nav">
                            <li><a style="padding:.5em" class="" href="https://www.linkedin.com/groups/13706636/"><img src="~/Images/LinkedIn.png" /></a></li>
                            <li><a style="padding:.5em" class="" href="https://www.instagram.com/centralia_college_foundation/"><img src="~/Images/Instagram.png" /></a></li>
                            <li><a style="padding:.5em" class="" href="https://www.facebook.com/CentraliaCollegeFoundation/"><img src="~/Images/Facebook.png" /></a></li>
                        </ul>
                    </div>
                    <br /><br /><br /><br />
                    <div id="header-content">
                        <ul class="navbar-nav">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (this.User.IsInRole("SuperAdmin") || this.User.IsInRole("Admin"))
                                {
                                    @if (this.User.IsInRole("SuperAdmin"))

                                    {
                                        <li class="nav-item">  
                                            <a class="nav-link text-dark navi" asp-area="" asp-controller="Role" asp-action="Index">Role Management</a>  
                                        </li>
                                    }                                  
                                    <li class="nav-item">                                    
                                        <a class="nav-link text-dark navi" asp-area="" asp-controller="AlumniUsers" asp-action="Index">Search</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark navi" id="register" asp-area="Identity" asp-page="/Account/Register">Add Alumni</a>
                                    </li>                                   
                                }
                                
                                else { }
                            }
                            else { }
                            <partial name="_LoginPartial" />
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="col-md-8 offset-md-2">
        <main role="main" class="@*pb-2*@ ">
            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    <br />
    <br />
    <footer class="footer text-muted">
        <div class="container footer">
            <div class="row footer">
                <div class="col-sm-2 offset-md-2">
                    <img style="padding-top:10px; padding-right:50px;"src="~/Images/CCF-Logo-yellow.png" />
                </div>
                <div style="padding:20px;"class="col-sm-2">
                    <p class="yellowed no-quarter">Contact Us:</p>
                    <p class="no-quarter">360-623-8942</p>
                    <p class="no-quarter">foundation@centralia.edu</p>
                </div>
                <div class="dashed-Vertical-Line"></div>
                <div style="padding:20px;"class="col-sm-2">
                    <p class="yellowed no-quarter">Find us:</p>
                    <p class="no-quarter">401 Centralia College Blvd</p>
                    
                </div>
                <div class="dashed-Vertical-Line"></div>
                <div style="padding:40px;"class="col-sm-2">
                    <ul class="navbar-nav">
                        <li>
                            <a href="https://www.linkedin.com/groups/13706636/" class="">
                                <img style="width:25px;height:25px;object-fit:cover;object-position:50% 50%" src="~/Images/footer-linkedin.webp" />
                            </a>
                            <a href="http://www.facebook.com/centraliacollegefoundation" class="">
                                <img style="width:25px;height:25px;object-fit:cover;object-position:50% 50%" src="~/Images/footer-facebook.png" />
                            </a>
                            <a href="https://www.instagram.com/centralia_college_foundation/" class="">
                                <img style="width:25px;height:25px;object-fit:cover;object-position:50% 50%" src="~/Images/footer-insta.png" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>